import { describe, expect, it, vi } from 'vitest';

vi.mock('../services/firebase', () => ({ db: {} }));
vi.mock('firebase/firestore', () => ({
  collection: vi.fn((_db, name: string) => ({ __col: name })),
  doc: vi.fn((_colOrDb: unknown, ...rest: unknown[]) => {
    // doc(collection(db, 'audit_log'), id) — the id is the last positional arg.
    const id = rest[rest.length - 1] as string;
    return { id, path: `audit_log/${id}` };
  }),
}));

import { writeAuditLog } from '../utils/auditLog';

describe('writeAuditLog (D10)', () => {
  it('writes a single entry to a doc id generated by crypto.randomUUID(), not a page-load counter', () => {
    const setSpy = vi.fn();
    const writer = { set: setSpy };
    writeAuditLog(writer, { actorMemberId: 'david-levy', action: 'account.save', target: 'accounts/a1' });
    expect(setSpy).toHaveBeenCalledTimes(1);
    const [ref, data] = setSpy.mock.calls[0];
    // A UUID (crypto.randomUUID() format), never a `${Date.now()}-${counter}` shape.
    expect(ref.id).toMatch(/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i);
    expect(data).toMatchObject({ actorMemberId: 'david-levy', action: 'account.save', target: 'accounts/a1' });
    expect(data.at).toEqual(expect.any(String));
  });

  it('two calls in the same millisecond never collide on id (the M1 bug)', () => {
    const ids = new Set<string>();
    const writer = { set: vi.fn((ref: { id?: string }) => { if (ref.id) ids.add(ref.id); }) };
    for (let i = 0; i < 50; i += 1) {
      writeAuditLog(writer, { actorMemberId: 'x', action: 'x.save', target: 'x/1' });
    }
    expect(ids.size).toBe(50); // every id unique — a Date.now()-counter scheme would collide
                                 // across two SEPARATE moduleCounter instances (two devices), not
                                 // within one process; this asserts randomUUID's own guarantee.
  });

  it('a Transaction (structurally identical set(ref, data) shape) satisfies the writer contract just like a WriteBatch', () => {
    // AuditWriter is structural, not WriteBatch-specific — this is the whole point of D10's
    // interface change: financeCollections.ts's new runTransaction-based save/remove pass a
    // Transaction here, and it must work with no special-casing.
    const txSet = vi.fn();
    const fakeTransaction = { get: vi.fn(), set: txSet, delete: vi.fn() };
    writeAuditLog(fakeTransaction, { actorMemberId: 'david-levy', action: 'loan.delete', target: 'loans/l1' });
    expect(txSet).toHaveBeenCalledTimes(1);
  });
});
