import { HttpsError, type FunctionsErrorCode } from 'firebase-functions/v2/https';
import { APIConnectionTimeoutError as AnthropicTimeoutError } from '@anthropic-ai/sdk';
import { APIConnectionTimeoutError as OpenAITimeoutError } from 'openai';
import { ApiError as GoogleApiError } from '@google/genai';

// Third-lens M2/D14 — every adapter call (aiChat.ts, aiExtractDocument.ts) is wrapped in a
// try/catch that runs the caught error through this mapper before it can reach onCall's default
// handler, which redacts anything that isn't already an HttpsError to a generic 'internal' — the
// same swallowed-error class D4/Sasha I4 already fixed once for cost-gate refusals.
//
// A reviewer instantiated the actual installed vendor SDK error classes and found the old
// message.includes('timeout') check dead against all three: Anthropic's and OpenAI's SDKs are
// both generated by the same Stainless toolchain and their client-side timeout class
// (APIConnectionTimeoutError) has `.name === 'Error'` and `.message === 'Request timed out.'` —
// which does not contain the substring "timeout". A real timeout from either vendor was silently
// falling through to the generic 'unknown' classification (wrong Hebrew copy, wrong HttpsError
// code) for what is likely the single most common LLM-call failure mode. Classification now
// checks the actual SDK error CLASS first — the class is a fact about what the SDK threw, not a
// guess about what its message happens to say this SDK version — falling back to a broadened
// message match ('timed out' as well as 'timeout') for shapes the class check can't cover (mocks,
// future SDK versions, non-SDK network errors).
//
// Google's @google/genai SDK has no dedicated timeout error class reachable from
// `models.generateContent` (the class hierarchy the .d.ts exposes for that call throws the single
// exported `ApiError`, carrying whatever HTTP status the server returned); its equivalent signal
// is `ApiError` with a 408 (Request Timeout) or 504 (Gateway Timeout) status. A client-side abort
// (request-level timeout with no server response at all) still throws a plain AbortError, already
// covered by the `name === 'AbortError'` check below.

export type ProviderFailureKind =
  | 'rate-limited' | 'timeout' | 'context-overflow' | 'unknown-model' | 'invalid-response' | 'unknown';

export function classifyProviderError(err: unknown): ProviderFailureKind {
  const e = err as { status?: number; code?: string; name?: string; message?: string } | undefined;
  const msg = (e?.message ?? '').toLowerCase();
  if (e?.status === 429) return 'rate-limited';
  if (
    err instanceof AnthropicTimeoutError ||
    err instanceof OpenAITimeoutError ||
    (err instanceof GoogleApiError && (err.status === 408 || err.status === 504)) ||
    e?.status === 408 || e?.status === 504 ||
    e?.name === 'AbortError' || e?.code === 'ETIMEDOUT' ||
    msg.includes('timeout') || msg.includes('timed out')
  ) return 'timeout';
  if (msg.includes('context length') || msg.includes('too many tokens') || msg.includes('maximum context')) return 'context-overflow';
  if (e?.status === 404 || msg.includes('model not found') || msg.includes('decommissioned')) return 'unknown-model';
  // 'json' alone is too broad — e.g. OpenAI's own 400 when response_format: json_object is
  // requested but the prompt doesn't contain the word "json" mentions "json" for an unrelated
  // (request-validation) reason. Require a co-occurring parse/format-failure word so this stays
  // narrow to genuine malformed-response wording ("Unexpected token ... in JSON", "invalid json",
  // "not valid JSON", "JSON parse error") without weakening real detection — `err instanceof
  // SyntaxError` (an actual JSON.parse() throw) is unaffected, checked independently of `msg`.
  if (err instanceof SyntaxError || (msg.includes('json') && /unexpected|parse|malformed|valid|syntax/.test(msg))) return 'invalid-response';
  return 'unknown';
}

const COPY_HE: Record<ProviderFailureKind, { code: FunctionsErrorCode; message: string }> = {
  'rate-limited': { code: 'resource-exhausted', message: 'ספק ה-AI עמוס כרגע — נסה שוב בעוד רגע.' },
  'timeout': { code: 'deadline-exceeded', message: 'הבקשה לספק ה-AI ארכה זמן רב מדי — נסה שוב.' },
  'context-overflow': { code: 'invalid-argument', message: 'התוכן שנשלח למודל גדול מדי או ארוך מדי עבור המודל שנבחר — נסה מודל אחר או קצר את הבקשה.' },
  'unknown-model': { code: 'invalid-argument', message: 'המודל שנבחר אינו זמין יותר אצל הספק — בחר מודל אחר בבורר.' },
  'invalid-response': { code: 'invalid-argument', message: 'התקבלה תשובה לא תקינה מהספק — נסה שוב או בחר מודל אחר.' },
  'unknown': { code: 'internal', message: 'קריאה ל-AI נכשלה מסיבה לא צפויה — נסה שוב, ואם זה חוזר על עצמו פנה לתמיכה.' },
};

/** Never throws a plain Error — every adapter-call failure becomes a real HttpsError with
 *  actionable Hebrew copy, so it survives onCall's default redaction of anything else to
 *  'internal' (the same swallowed-error class D4/Sasha I4 already fixed for cost refusals).
 *  `context` is accepted for future per-context copy variance; both callers today share copy. */
export function toAiHttpsError(err: unknown, _context: 'chat' | 'extraction'): HttpsError {
  const kind = classifyProviderError(err);
  const { code, message } = COPY_HE[kind];
  return new HttpsError(code, message);
}
